// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package db

import (
	"context"
	"time"
)

const countValidAlertsByUser = `-- name: CountValidAlertsByUser :many
SELECT userId, COUNT(*) AS count
FROM alerts
WHERE status = 'ABNORMAL'
  AND alerted_at >= ?
  AND alerted_at < ?
GROUP BY userId
`

type CountValidAlertsByUserParams struct {
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

type CountValidAlertsByUserRow struct {
	Userid uint32 `json:"userid"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountValidAlertsByUser(ctx context.Context, arg CountValidAlertsByUserParams) ([]CountValidAlertsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, countValidAlertsByUser, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountValidAlertsByUserRow{}
	for rows.Next() {
		var i CountValidAlertsByUserRow
		if err := rows.Scan(&i.Userid, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
