// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countValidAlertsByUser = `-- name: CountValidAlertsByUser :many
SELECT userId, COUNT(*) AS count
FROM alerts
WHERE status = 'ABNORMAL'
  AND alerted_at >= ?
  AND alerted_at < ?
GROUP BY userId
`

type CountValidAlertsByUserParams struct {
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

type CountValidAlertsByUserRow struct {
	Userid uint32 `json:"userid"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountValidAlertsByUser(ctx context.Context, arg CountValidAlertsByUserParams) ([]CountValidAlertsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, countValidAlertsByUser, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountValidAlertsByUserRow{}
	for rows.Next() {
		var i CountValidAlertsByUserRow
		if err := rows.Scan(&i.Userid, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAlert = `-- name: CreateAlert :execresult
INSERT INTO alerts (userId, type, reason, status)
VALUES (?, ?, ?, 'PENDING')
`

type CreateAlertParams struct {
	Userid uint32     `json:"userid"`
	Type   AlertsType `json:"type"`
	Reason string     `json:"reason"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAlert, arg.Userid, arg.Type, arg.Reason)
}

const linkAlertTrade = `-- name: LinkAlertTrade :exec
INSERT INTO alert_trades (alertId, tradeId)
VALUES (?, ?)
`

type LinkAlertTradeParams struct {
	Alertid uint64 `json:"alertid"`
	Tradeid uint64 `json:"tradeid"`
}

func (q *Queries) LinkAlertTrade(ctx context.Context, arg LinkAlertTradeParams) error {
	_, err := q.db.ExecContext(ctx, linkAlertTrade, arg.Alertid, arg.Tradeid)
	return err
}
