// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cross_trading.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const claimCrossTradingAlert = `-- name: ClaimCrossTradingAlert :execresult
UPDATE cross_trading_count
SET alerted = TRUE
WHERE userId = ? AND date = ? AND alerted = FALSE
`

type ClaimCrossTradingAlertParams struct {
	Userid uint32    `json:"userid"`
	Date   time.Time `json:"date"`
}

func (q *Queries) ClaimCrossTradingAlert(ctx context.Context, arg ClaimCrossTradingAlertParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, claimCrossTradingAlert, arg.Userid, arg.Date)
}

const upsertCrossTradingCount = `-- name: UpsertCrossTradingCount :execresult
INSERT INTO cross_trading_count (userId, date, count)
VALUES (?, ?, LAST_INSERT_ID(1))
ON DUPLICATE KEY UPDATE count = LAST_INSERT_ID(count + 1)
`

type UpsertCrossTradingCountParams struct {
	Userid uint32    `json:"userid"`
	Date   time.Time `json:"date"`
}

func (q *Queries) UpsertCrossTradingCount(ctx context.Context, arg UpsertCrossTradingCountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertCrossTradingCount, arg.Userid, arg.Date)
}
