// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cursors.sql

package db

import (
	"context"
	"time"
)

const getCursor = `-- name: GetCursor :one
SELECT timestamp FROM cursors
WHERE type = ?
LIMIT 1
`

func (q *Queries) GetCursor(ctx context.Context, type_ string) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getCursor, type_)
	var timestamp time.Time
	err := row.Scan(&timestamp)
	return timestamp, err
}

const upsertCursor = `-- name: UpsertCursor :exec
INSERT INTO cursors (type, timestamp)
VALUES (?, ?)
ON DUPLICATE KEY UPDATE timestamp = VALUES(timestamp)
`

type UpsertCursorParams struct {
	Type      string    `json:"type"`
	Timestamp time.Time `json:"timestamp"`
}

func (q *Queries) UpsertCursor(ctx context.Context, arg UpsertCursorParams) error {
	_, err := q.db.ExecContext(ctx, upsertCursor, arg.Type, arg.Timestamp)
	return err
}
