// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type AlertsStatus string

const (
	AlertsStatusPENDING  AlertsStatus = "PENDING"
	AlertsStatusNORMAL   AlertsStatus = "NORMAL"
	AlertsStatusABNORMAL AlertsStatus = "ABNORMAL"
)

func (e *AlertsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertsStatus(s)
	case string:
		*e = AlertsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertsStatus: %T", src)
	}
	return nil
}

type NullAlertsStatus struct {
	AlertsStatus AlertsStatus `json:"alerts_status"`
	Valid        bool         `json:"valid"` // Valid is true if AlertsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AlertsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertsStatus), nil
}

type AlertsType string

const (
	AlertsTypeCROSSTRADING     AlertsType = "CROSS_TRADING"
	AlertsTypeLARGETRANSACTION AlertsType = "LARGE_TRANSACTION"
	AlertsTypeABNORMALTRANSFER AlertsType = "ABNORMAL_TRANSFER"
)

func (e *AlertsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertsType(s)
	case string:
		*e = AlertsType(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertsType: %T", src)
	}
	return nil
}

type NullAlertsType struct {
	AlertsType AlertsType `json:"alerts_type"`
	Valid      bool       `json:"valid"` // Valid is true if AlertsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertsType) Scan(value interface{}) error {
	if value == nil {
		ns.AlertsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertsType), nil
}

type UsersAssetTier string

const (
	UsersAssetTierLOW    UsersAssetTier = "LOW"
	UsersAssetTierMEDIUM UsersAssetTier = "MEDIUM"
	UsersAssetTierHIGH   UsersAssetTier = "HIGH"
)

func (e *UsersAssetTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersAssetTier(s)
	case string:
		*e = UsersAssetTier(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersAssetTier: %T", src)
	}
	return nil
}

type NullUsersAssetTier struct {
	UsersAssetTier UsersAssetTier `json:"users_asset_tier"`
	Valid          bool           `json:"valid"` // Valid is true if UsersAssetTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersAssetTier) Scan(value interface{}) error {
	if value == nil {
		ns.UsersAssetTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersAssetTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersAssetTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersAssetTier), nil
}

type UsersRiskLevel string

const (
	UsersRiskLevelLOW    UsersRiskLevel = "LOW"
	UsersRiskLevelMEDIUM UsersRiskLevel = "MEDIUM"
	UsersRiskLevelHIGH   UsersRiskLevel = "HIGH"
)

func (e *UsersRiskLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRiskLevel(s)
	case string:
		*e = UsersRiskLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRiskLevel: %T", src)
	}
	return nil
}

type NullUsersRiskLevel struct {
	UsersRiskLevel UsersRiskLevel `json:"users_risk_level"`
	Valid          bool           `json:"valid"` // Valid is true if UsersRiskLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRiskLevel) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRiskLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRiskLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRiskLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRiskLevel), nil
}

type Alert struct {
	ID          uint64       `json:"id"`
	Userid      uint32       `json:"userid"`
	Type        AlertsType   `json:"type"`
	Reason      string       `json:"reason"`
	Status      AlertsStatus `json:"status"`
	AlertedAt   time.Time    `json:"alerted_at"`
	ProcessedAt sql.NullTime `json:"processed_at"`
}

type AlertTrade struct {
	ID        uint32    `json:"id"`
	Alertid   uint64    `json:"alertid"`
	Tradeid   uint64    `json:"tradeid"`
	CreatedAt time.Time `json:"created_at"`
}

type AlertTransfer struct {
	ID         uint32    `json:"id"`
	Alertid    uint64    `json:"alertid"`
	Transferid uint64    `json:"transferid"`
	CreatedAt  time.Time `json:"created_at"`
}

type CrossTradingCount struct {
	ID        uint32    `json:"id"`
	Userid    uint32    `json:"userid"`
	Date      time.Time `json:"date"`
	Count     uint32    `json:"count"`
	Alerted   bool      `json:"alerted"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Cursor struct {
	ID        uint32    `json:"id"`
	Type      string    `json:"type"`
	Timestamp time.Time `json:"timestamp"`
}

type TransferHourSum struct {
	ID        uint32    `json:"id"`
	Userid    uint32    `json:"userid"`
	Hour      time.Time `json:"hour"`
	Amount    uint64    `json:"amount"`
	Alerted   bool      `json:"alerted"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID           uint32         `json:"id"`
	AverageAsset string         `json:"average_asset"`
	RiskLevel    UsersRiskLevel `json:"risk_level"`
	AssetTier    UsersAssetTier `json:"asset_tier"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
