// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountValidAlertsByUser(ctx context.Context, arg CountValidAlertsByUserParams) ([]CountValidAlertsByUserRow, error)
	ListUserRiskLevels(ctx context.Context) ([]ListUserRiskLevelsRow, error)
	UpdateUserRiskLevel(ctx context.Context, arg UpdateUserRiskLevelParams) error
	UpsertUserAssetTier(ctx context.Context, arg UpsertUserAssetTierParams) error
}

var _ Querier = (*Queries)(nil)
