// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfer_hour_sum.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const claimTransferAlert = `-- name: ClaimTransferAlert :execresult
UPDATE transfer_hour_sum
SET alerted = TRUE
WHERE userId = ? AND hour = ? AND alerted = FALSE
`

type ClaimTransferAlertParams struct {
	Userid uint32    `json:"userid"`
	Hour   time.Time `json:"hour"`
}

func (q *Queries) ClaimTransferAlert(ctx context.Context, arg ClaimTransferAlertParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, claimTransferAlert, arg.Userid, arg.Hour)
}

const getTransferHourSum = `-- name: GetTransferHourSum :one
SELECT amount FROM transfer_hour_sum
WHERE userId = ? AND hour = ?
LIMIT 1
`

type GetTransferHourSumParams struct {
	Userid uint32    `json:"userid"`
	Hour   time.Time `json:"hour"`
}

func (q *Queries) GetTransferHourSum(ctx context.Context, arg GetTransferHourSumParams) (uint64, error) {
	row := q.db.QueryRowContext(ctx, getTransferHourSum, arg.Userid, arg.Hour)
	var amount uint64
	err := row.Scan(&amount)
	return amount, err
}

const upsertTransferHourSum = `-- name: UpsertTransferHourSum :exec
INSERT INTO transfer_hour_sum (userId, hour, amount)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE amount = amount + VALUES(amount)
`

type UpsertTransferHourSumParams struct {
	Userid uint32    `json:"userid"`
	Hour   time.Time `json:"hour"`
	Amount uint64    `json:"amount"`
}

func (q *Queries) UpsertTransferHourSum(ctx context.Context, arg UpsertTransferHourSumParams) error {
	_, err := q.db.ExecContext(ctx, upsertTransferHourSum, arg.Userid, arg.Hour, arg.Amount)
	return err
}
