// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, average_asset, risk_level, asset_tier, updated_at FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uint32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AverageAsset,
		&i.RiskLevel,
		&i.AssetTier,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserRiskLevels = `-- name: ListUserRiskLevels :many
SELECT id, risk_level FROM users
ORDER BY id
`

type ListUserRiskLevelsRow struct {
	ID        uint32         `json:"id"`
	RiskLevel UsersRiskLevel `json:"risk_level"`
}

func (q *Queries) ListUserRiskLevels(ctx context.Context) ([]ListUserRiskLevelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserRiskLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRiskLevelsRow{}
	for rows.Next() {
		var i ListUserRiskLevelsRow
		if err := rows.Scan(&i.ID, &i.RiskLevel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, average_asset, risk_level, asset_tier, updated_at FROM users
ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.AverageAsset,
			&i.RiskLevel,
			&i.AssetTier,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserRiskLevel = `-- name: UpdateUserRiskLevel :exec
UPDATE users
SET risk_level = ?
WHERE id = ?
`

type UpdateUserRiskLevelParams struct {
	RiskLevel UsersRiskLevel `json:"risk_level"`
	ID        uint32         `json:"id"`
}

func (q *Queries) UpdateUserRiskLevel(ctx context.Context, arg UpdateUserRiskLevelParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRiskLevel, arg.RiskLevel, arg.ID)
	return err
}

const upsertUserAssetTier = `-- name: UpsertUserAssetTier :exec
INSERT INTO users (id, average_asset, asset_tier)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE
    average_asset = VALUES(average_asset),
    asset_tier = VALUES(asset_tier)
`

type UpsertUserAssetTierParams struct {
	ID           uint32         `json:"id"`
	AverageAsset string         `json:"average_asset"`
	AssetTier    UsersAssetTier `json:"asset_tier"`
}

func (q *Queries) UpsertUserAssetTier(ctx context.Context, arg UpsertUserAssetTierParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserAssetTier, arg.ID, arg.AverageAsset, arg.AssetTier)
	return err
}
