// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const upsertUserAssetTier = `-- name: UpsertUserAssetTier :exec
INSERT INTO users (id, average_asset, asset_tier)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE
    average_asset = VALUES(average_asset),
    asset_tier = VALUES(asset_tier)
`

type UpsertUserAssetTierParams struct {
	ID           uint32         `json:"id"`
	AverageAsset string         `json:"average_asset"`
	AssetTier    UsersAssetTier `json:"asset_tier"`
}

func (q *Queries) UpsertUserAssetTier(ctx context.Context, arg UpsertUserAssetTierParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserAssetTier, arg.ID, arg.AverageAsset, arg.AssetTier)
	return err
}
