// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package sourcedb

import (
	"context"
)

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, account_number, balance, available_balance, status
FROM accounts
WHERE id = ?
LIMIT 1
`

type GetAccountRow struct {
	ID               int32          `json:"id"`
	UserID           int32          `json:"user_id"`
	AccountNumber    int32          `json:"account_number"`
	Balance          uint64         `json:"balance"`
	AvailableBalance uint64         `json:"available_balance"`
	Status           AccountsStatus `json:"status"`
}

func (q *Queries) GetAccount(ctx context.Context, id int32) (GetAccountRow, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountNumber,
		&i.Balance,
		&i.AvailableBalance,
		&i.Status,
	)
	return i, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, account_number, balance, available_balance, status
FROM accounts
WHERE user_id = ?
ORDER BY id
`

type ListAccountsByUserRow struct {
	ID               int32          `json:"id"`
	AccountNumber    int32          `json:"account_number"`
	Balance          uint64         `json:"balance"`
	AvailableBalance uint64         `json:"available_balance"`
	Status           AccountsStatus `json:"status"`
}

func (q *Queries) ListAccountsByUser(ctx context.Context, userID int32) ([]ListAccountsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsByUserRow{}
	for rows.Next() {
		var i ListAccountsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountNumber,
			&i.Balance,
			&i.AvailableBalance,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockHoldingsByAccount = `-- name: ListStockHoldingsByAccount :many
SELECT s.id AS stock_id, s.name, us.quantity, us.average, s.price
FROM user_stocks us
JOIN stocks s ON s.id = us.stock_id
WHERE us.account_id = ?
ORDER BY s.id
`

type ListStockHoldingsByAccountRow struct {
	StockID  int32  `json:"stock_id"`
	Name     string `json:"name"`
	Quantity uint64 `json:"quantity"`
	Average  uint64 `json:"average"`
	Price    uint64 `json:"price"`
}

func (q *Queries) ListStockHoldingsByAccount(ctx context.Context, accountID int32) ([]ListStockHoldingsByAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listStockHoldingsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockHoldingsByAccountRow{}
	for rows.Next() {
		var i ListStockHoldingsByAccountRow
		if err := rows.Scan(
			&i.StockID,
			&i.Name,
			&i.Quantity,
			&i.Average,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
