// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset.sql

package sourcedb

import (
	"context"
)

const getUserCashBalance = `-- name: GetUserCashBalance :one
SELECT COALESCE(SUM(balance), 0) AS cash
FROM accounts
WHERE user_id = ?
`

func (q *Queries) GetUserCashBalance(ctx context.Context, userID int32) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getUserCashBalance, userID)
	var cash interface{}
	err := row.Scan(&cash)
	return cash, err
}

const getUserStockValue = `-- name: GetUserStockValue :one
SELECT COALESCE(SUM(us.quantity * s.price), 0) AS stock_value
FROM user_stocks us
JOIN accounts a ON a.id = us.account_id
JOIN stocks s ON s.id = us.stock_id
WHERE a.user_id = ?
`

func (q *Queries) GetUserStockValue(ctx context.Context, userID int32) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getUserStockValue, userID)
	var stock_value interface{}
	err := row.Scan(&stock_value)
	return stock_value, err
}

const listUserIDs = `-- name: ListUserIDs :many
SELECT id FROM users
ORDER BY id
`

func (q *Queries) ListUserIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, listUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
