// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sourcedb

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type AccountsStatus string

const (
	AccountsStatusPENDING AccountsStatus = "PENDING"
	AccountsStatusACTIVE  AccountsStatus = "ACTIVE"
)

func (e *AccountsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountsStatus(s)
	case string:
		*e = AccountsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountsStatus: %T", src)
	}
	return nil
}

type NullAccountsStatus struct {
	AccountsStatus AccountsStatus `json:"accounts_status"`
	Valid          bool           `json:"valid"` // Valid is true if AccountsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountsStatus), nil
}

type StocksStatus string

const (
	StocksStatusPENDING   StocksStatus = "PENDING"
	StocksStatusLISTED    StocksStatus = "LISTED"
	StocksStatusSUSPENDED StocksStatus = "SUSPENDED"
	StocksStatusDELISTED  StocksStatus = "DELISTED"
)

func (e *StocksStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StocksStatus(s)
	case string:
		*e = StocksStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StocksStatus: %T", src)
	}
	return nil
}

type NullStocksStatus struct {
	StocksStatus StocksStatus `json:"stocks_status"`
	Valid        bool         `json:"valid"` // Valid is true if StocksStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStocksStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StocksStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StocksStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStocksStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StocksStatus), nil
}

type Account struct {
	ID               int32          `json:"id"`
	UserID           int32          `json:"user_id"`
	AccountNumber    int32          `json:"account_number"`
	Balance          uint64         `json:"balance"`
	AvailableBalance uint64         `json:"available_balance"`
	Status           AccountsStatus `json:"status"`
	PublishedAt      sql.NullTime   `json:"published_at"`
	CreatedAt        time.Time      `json:"created_at"`
}

type Stock struct {
	ID           int32        `json:"id"`
	Name         string       `json:"name"`
	Price        uint64       `json:"price"`
	ListingPrice uint64       `json:"listing_price"`
	Status       StocksStatus `json:"status"`
	PublishedAt  sql.NullTime `json:"published_at"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

type UserStock struct {
	AccountID         int32  `json:"account_id"`
	StockID           int32  `json:"stock_id"`
	Quantity          uint64 `json:"quantity"`
	AvailableQuantity uint64 `json:"available_quantity"`
	Average           uint64 `json:"average"`
	TotalBuyAmount    uint64 `json:"total_buy_amount"`
}
