// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sourcedb

import (
	"context"
	"time"
)

type Querier interface {
	GetAccount(ctx context.Context, id int32) (GetAccountRow, error)
	GetUserCashBalance(ctx context.Context, userID int32) (interface{}, error)
	GetUserStockValue(ctx context.Context, userID int32) (interface{}, error)
	ListAccountsByUser(ctx context.Context, userID int32) ([]ListAccountsByUserRow, error)
	ListStockHoldingsByAccount(ctx context.Context, accountID int32) ([]ListStockHoldingsByAccountRow, error)
	ListTradesSince(ctx context.Context, matchedAt time.Time) ([]ListTradesSinceRow, error)
	ListUserIDs(ctx context.Context) ([]int32, error)
}

var _ Querier = (*Queries)(nil)
