// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sourcedb

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	GetAccount(ctx context.Context, id int32) (GetAccountRow, error)
	GetTradeDetail(ctx context.Context, id int64) (GetTradeDetailRow, error)
	GetTransferDetail(ctx context.Context, id int64) (GetTransferDetailRow, error)
	GetUserCashBalance(ctx context.Context, userID int32) (interface{}, error)
	GetUserStockValue(ctx context.Context, userID int32) (interface{}, error)
	ListAccountsByUser(ctx context.Context, userID int32) ([]ListAccountsByUserRow, error)
	ListReceivedTransfersByUserAndHour(ctx context.Context, arg ListReceivedTransfersByUserAndHourParams) ([]ListReceivedTransfersByUserAndHourRow, error)
	ListSelfTradesByUserAndDate(ctx context.Context, arg ListSelfTradesByUserAndDateParams) ([]ListSelfTradesByUserAndDateRow, error)
	ListStockHoldingsByAccount(ctx context.Context, accountID int32) ([]ListStockHoldingsByAccountRow, error)
	ListTradesSince(ctx context.Context, matchedAt time.Time) ([]ListTradesSinceRow, error)
	ListTransfersSince(ctx context.Context, completedAt sql.NullTime) ([]ListTransfersSinceRow, error)
	ListUserIDs(ctx context.Context) ([]int32, error)
}

var _ Querier = (*Queries)(nil)
