// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sourcedb

import (
	"context"
)

type Querier interface {
	GetUserCashBalance(ctx context.Context, userID int32) (interface{}, error)
	GetUserStockValue(ctx context.Context, userID int32) (interface{}, error)
	ListUserIDs(ctx context.Context) ([]int32, error)
}

var _ Querier = (*Queries)(nil)
