// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trade.sql

package sourcedb

import (
	"context"
	"time"
)

const getTradeDetail = `-- name: GetTradeDetail :one
SELECT
    t.id AS trade_id,
    t.stock_id,
    t.quantity,
    t.price,
    t.matched_at,
    ma.user_id AS maker_user_id,
    ka.user_id AS taker_user_id
FROM trades t
JOIN orders mo ON mo.id = t.maker_order_id
JOIN accounts ma ON ma.id = mo.account_id
JOIN orders ko ON ko.id = t.taker_order_id
JOIN accounts ka ON ka.id = ko.account_id
WHERE t.id = ?
LIMIT 1
`

type GetTradeDetailRow struct {
	TradeID     int64     `json:"trade_id"`
	StockID     int32     `json:"stock_id"`
	Quantity    uint64    `json:"quantity"`
	Price       uint64    `json:"price"`
	MatchedAt   time.Time `json:"matched_at"`
	MakerUserID int32     `json:"maker_user_id"`
	TakerUserID int32     `json:"taker_user_id"`
}

func (q *Queries) GetTradeDetail(ctx context.Context, id int64) (GetTradeDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getTradeDetail, id)
	var i GetTradeDetailRow
	err := row.Scan(
		&i.TradeID,
		&i.StockID,
		&i.Quantity,
		&i.Price,
		&i.MatchedAt,
		&i.MakerUserID,
		&i.TakerUserID,
	)
	return i, err
}

const listSelfTradesByUserAndDate = `-- name: ListSelfTradesByUserAndDate :many
SELECT
    t.id AS trade_id,
    t.quantity,
    t.price,
    t.matched_at
FROM trades t
JOIN orders mo ON mo.id = t.maker_order_id
JOIN accounts ma ON ma.id = mo.account_id
JOIN orders ko ON ko.id = t.taker_order_id
JOIN accounts ka ON ka.id = ko.account_id
WHERE ma.user_id = ?
  AND ka.user_id = ?
  AND DATE(t.matched_at) = ?
ORDER BY t.matched_at
`

type ListSelfTradesByUserAndDateParams struct {
	UserID int32     `json:"user_id"`
	Date   time.Time `json:"date"`
}

type ListSelfTradesByUserAndDateRow struct {
	TradeID   int64     `json:"trade_id"`
	Quantity  uint64    `json:"quantity"`
	Price     uint64    `json:"price"`
	MatchedAt time.Time `json:"matched_at"`
}

func (q *Queries) ListSelfTradesByUserAndDate(ctx context.Context, arg ListSelfTradesByUserAndDateParams) ([]ListSelfTradesByUserAndDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listSelfTradesByUserAndDate, arg.UserID, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSelfTradesByUserAndDateRow{}
	for rows.Next() {
		var i ListSelfTradesByUserAndDateRow
		if err := rows.Scan(
			&i.TradeID,
			&i.Quantity,
			&i.Price,
			&i.MatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTradesSince = `-- name: ListTradesSince :many
SELECT
    t.id AS trade_id,
    t.quantity,
    t.price,
    t.matched_at,
    ma.user_id AS maker_user_id,
    ka.user_id AS taker_user_id
FROM trades t
JOIN orders mo ON mo.id = t.maker_order_id
JOIN accounts ma ON ma.id = mo.account_id
JOIN orders ko ON ko.id = t.taker_order_id
JOIN accounts ka ON ka.id = ko.account_id
WHERE t.matched_at > ?
ORDER BY t.matched_at
`

type ListTradesSinceRow struct {
	TradeID     int64     `json:"trade_id"`
	Quantity    uint64    `json:"quantity"`
	Price       uint64    `json:"price"`
	MatchedAt   time.Time `json:"matched_at"`
	MakerUserID int32     `json:"maker_user_id"`
	TakerUserID int32     `json:"taker_user_id"`
}

func (q *Queries) ListTradesSince(ctx context.Context, matchedAt time.Time) ([]ListTradesSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listTradesSince, matchedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTradesSinceRow{}
	for rows.Next() {
		var i ListTradesSinceRow
		if err := rows.Scan(
			&i.TradeID,
			&i.Quantity,
			&i.Price,
			&i.MatchedAt,
			&i.MakerUserID,
			&i.TakerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
