// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfer.sql

package sourcedb

import (
	"context"
	"database/sql"
	"time"
)

const getTransferDetail = `-- name: GetTransferDetail :one
SELECT
    t.id AS transfer_id,
    t.amount,
    t.status,
    t.created_at,
    t.completed_at,
    sa.user_id AS sender_user_id,
    ra.user_id AS recipient_user_id
FROM transfers t
JOIN accounts sa ON sa.id = t.sender_account_id
JOIN accounts ra ON ra.id = t.recipient_account_id
WHERE t.id = ?
LIMIT 1
`

type GetTransferDetailRow struct {
	TransferID      int64           `json:"transfer_id"`
	Amount          uint64          `json:"amount"`
	Status          TransfersStatus `json:"status"`
	CreatedAt       time.Time       `json:"created_at"`
	CompletedAt     sql.NullTime    `json:"completed_at"`
	SenderUserID    int32           `json:"sender_user_id"`
	RecipientUserID int32           `json:"recipient_user_id"`
}

func (q *Queries) GetTransferDetail(ctx context.Context, id int64) (GetTransferDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getTransferDetail, id)
	var i GetTransferDetailRow
	err := row.Scan(
		&i.TransferID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.SenderUserID,
		&i.RecipientUserID,
	)
	return i, err
}
